[package]
name = "simple_file_logger"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/mendelsshop/simple_file_logger"
keywords = ["logging", "logger", "file_logger", "log"]
categories = ["logging::loggers", "log", "logging"]
description = "A simple file logger for Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
flexi_logger = "0.23.1"