on:
  push:
    branches: [main]
  pull_request:

name: codecov
jobs:
  codecov: 
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
